# 此文件展示了Meilisearch的默认配置
# 所有变量定义详见：https://www.meilisearch.com/docs/learn/configuration/instance_options#environment-variables

# 指定数据库文件创建和读取的位置
# https://www.meilisearch.com/docs/learn/configuration/instance_options#database-path
db_path = "./data.ms"

# 配置实例环境。值必须为`production`或`development`
# https://www.meilisearch.com/docs/learn/configuration/instance_options#environment
env = "development"

# HTTP服务器的监听地址
http_addr = "localhost:7700"

# 设置实例的主密钥，自动保护除GET /health外的所有路由
# https://www.meilisearch.com/docs/learn/configuration/instance_options#master-key
master_key = "gnRmBsBY5Mp6wtgKA06riGo5Ta7-WifD9OxAyENffQs"

# 当提供此标志时，禁用Meilisearch内置的遥测功能
# Meilisearch会自动收集未使用此标志退出的所有实例的数据
# 所有收集的数据仅用于改进Meilisearch，可随时删除
# https://www.meilisearch.com/docs/learn/configuration/instance_options#disable-analytics
# no_analytics = true

# 设置接受payload的最大尺寸
# https://www.meilisearch.com/docs/learn/configuration/instance_options#payload-limit-size
http_payload_size_limit = "100 MB"

# 定义Meilisearch日志应包含的详细程度
# Meilisearch当前支持六种日志级别，按详细程度递增排序：`OFF`、`ERROR`、`WARN`、`INFO`、`DEBUG`、`TRACE`
# https://www.meilisearch.com/docs/learn/configuration/instance_options#log-level
log_level = "INFO"

# 设置索引时Meilisearch可使用的最大内存量
# https://www.meilisearch.com/docs/learn/configuration/instance_options#max-indexing-memory
# max_indexing_memory = "2 GiB"

# 设置索引时Meilisearch可使用的最大线程数
# https://www.meilisearch.com/docs/learn/configuration/instance_options#max-indexing-threads
# max_indexing_threads = 4

#############
### 转储 ###
#############

# 设置Meilisearch创建转储文件的目录
# https://www.meilisearch.com/docs/learn/configuration/instance_options#dump-directory
dump_dir = "dumps/"

# 导入指定路径的转储文件。路径必须指向.dump文件
# https://www.meilisearch.com/docs/learn/configuration/instance_options#import-dump
# import_dump = "./path/to/my/file.dump"

# 当`import_dump`未指向有效转储文件时，阻止Meilisearch抛出错误
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ignore-missing-dump
ignore_missing_dump = false

# 当使用`import_dump`时，阻止已有数据库的Meilisearch实例抛出错误
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ignore-dump-if-db-exists
ignore_dump_if_db_exists = false


#################
### 快照 ###
#################

# 当为true时启用定时快照，为false时禁用（默认）
# 如果值为整数，则启用定时快照，并将该值作为快照间隔时间（秒）
# https://www.meilisearch.com/docs/learn/configuration/instance_options#schedule-snapshot-creation
schedule_snapshot = false

# 设置Meilisearch存储快照的目录
# https://www.meilisearch.com/docs/learn/configuration/instance_options#snapshot-destination
snapshot_dir = "snapshots/"

# 导入指定路径的快照文件后启动Meilisearch
# https://www.meilisearch.com/docs/learn/configuration/instance_options#import-snapshot
# import_snapshot = "./path/to/my/snapshot"

# 当`import_snapshot`未指向有效快照文件时，阻止Meilisearch抛出错误
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ignore-missing-snapshot
ignore_missing_snapshot = false

# 当使用`import_snapshot`时，阻止已有数据库的Meilisearch实例抛出错误
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ignore-snapshot-if-db-exists
ignore_snapshot_if_db_exists = false


###########
### SSL ###
###########

# 在指定路径启用客户端认证
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-authentication-path
# ssl_auth_path = "./path/to/root"

# 设置服务器的SSL证书
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-certificates-path
# ssl_cert_path = "./path/to/certfile"

# 设置服务器的SSL密钥文件
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-key-path
# ssl_key_path = "./path/to/private-key"

# 设置服务器的OCSP文件
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-ocsp-path
# ssl_ocsp_path = "./path/to/ocsp-file"

# 使SSL认证成为强制要求
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-require-auth
ssl_require_auth = false

# 启用SSL会话恢复
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-resumption
ssl_resumption = false

# 启用SSL票据
# https://www.meilisearch.com/docs/learn/configuration/instance_options#ssl-tickets
ssl_tickets = false

#############################
### 实验性功能 ###
#############################

# 实验性指标功能。详见：<https://github.com/meilisearch/meilisearch/discussions/3518>
# 在`GET /metrics`端点启用Prometheus指标
experimental_enable_metrics = false

# 实验性减少索引期间内存使用，请勿在生产环境使用，详见：<https://github.com/meilisearch/product/discussions/652>
experimental_reduce_indexing_memory_usage = false

# 实验性减少批量处理任务的最大数量，详见：<https://github.com/orgs/meilisearch/discussions/713>
# experimental_max_number_of_batched_tasks = 100